name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            name: linux
            bin: smaug
          - os: macos-latest
            name: mac
            bin: smaug
          - os: windows-latest
            name: windows
            bin: smaug.exe

    runs-on: ${{matrix.os }}

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy
    - uses: actions/checkout@v2
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: -- -D warnings
    - name: Run tests
      run: cargo test --verbose
    - name: build
      run: cargo build --release --locked
    - name: artifacts
      uses: actions/upload-artifact@v2
      with:
        name: smaug-${{matrix.name}}
        path: target/release/${{matrix.bin}}

